"""Tags

Revision ID: 314b1598e986
Revises: cdff4502de8d
Create Date: 2025-06-14 16:34:26.288217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314b1598e986'
down_revision = 'cdff4502de8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('note_tags',
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.drop_table('note_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
